//+------------------------------------------------------------------+
//|                                                 LondonBreakoutEA |
//|                               Generated by ChatGPT (gpt-5-codex) |
//+------------------------------------------------------------------+
#property copyright "Generated by ChatGPT"
#property link      ""
#property version   "1.00"
#property strict

//--- Input parameters -------------------------------------------------
input string TELEGRAM_TOKEN      = "";        // Telegram bot token from @BotFather
input string TELEGRAM_CHAT_ID    = "";        // Telegram chat/channel identifier (can be negative)
input string TradeSymbol         = _Symbol;   // Symbol to trade (supports broker suffixes)
input bool   EnableTrading       = false;     // Enable automated order placement
input long   MagicNumber         = 123456;    // Magic number for identifying EA trades
input ENUM_TIMEFRAMES RangeTF    = PERIOD_M15;// Timeframe used to compute Asian range and indicators
input int    AsianStartHour      = 0;         // Start hour of the Asian session
input int    AsianEndHour        = 7;         // Exclusive end hour of the Asian session
input int    TradeStartHour      = 8;         // London session start hour (pending order placement)
input int    TradeEndHour        = 12;        // London session end hour (cancel unfilled orders)
input bool   UseGMT              = false;     // Use GMT time basis instead of server time
input int    ManualGMTOffsetHours= 0;         // GMT offset hours to subtract from server time when UseGMT=true
input int    EMAPeriod           = 200;       // EMA period for directional bias
input int    RSIperiod           = 14;        // RSI period for momentum filter
input int    RSILongMin          = 55;        // Minimum RSI value for long confirmation
input int    RSIShortMax         = 45;        // Maximum RSI value for short confirmation
input int    ATRperiod           = 14;        // ATR period for risk management
input double SL_ATR_mult         = 1.5;       // ATR multiplier for stop-loss distance
input double RR_TP               = 1.5;       // Take-profit distance multiplier (Risk * RR_TP)
input double RiskPercent         = 0.7;       // Percentage of balance risked per trade
input bool   OnlyOneSideTrend    = true;      // Trade only in EMA trend direction if true
input int    BufferPoints        = 200;       // Buffer points added above/below the Asian range
input int    MaxSpreadPoints     = 600;       // Maximum spread allowed to place pending order
input bool   MoveToBE_At1R       = true;      // Move stop to break-even at 1R
input bool   TrailAfter1R        = true;      // Trail stop after break-even using ATR
input double Trail_ATR_mult      = 1.0;       // ATR multiplier for trailing stop distance
input int    Slippage            = 30;        // Maximum slippage in points when sending orders
input int    MinSLUpdatePoints   = 30;        // Minimum SL change in points to modify
input int    MinSLUpdateSeconds  = 20;        // Minimum seconds between SL modifications

//--- Indicator handles ------------------------------------------------
int  g_handleEMA = INVALID_HANDLE;
int  g_handleRSI = INVALID_HANDLE;
int  g_handleATR = INVALID_HANDLE;

//--- Asian range state ------------------------------------------------
double   g_AsianHigh          = 0.0;
double   g_AsianLow           = 0.0;
bool     g_RangeCalculated    = false;
datetime g_CurrentDayStart    = 0;
bool     g_RangeAnnounced     = false;

//--- Pending order and trade state -----------------------------------
bool     g_TradePlacedToday   = false;
bool     g_SignalSentBuyToday = false;
bool     g_SignalSentSellToday= false;
bool     g_PositionActive     = false;
bool     g_MoveToBE_Done      = false;
double   g_LastRiskDistance   = 0.0;
double   g_LastEntryPrice     = 0.0;
double   g_LastStopLoss       = 0.0;
datetime g_LastSLUpdateTime   = 0;

ulong    g_BuyStopTicket      = 0;
ulong    g_SellStopTicket     = 0;

//+------------------------------------------------------------------+
//| Escape special characters for JSON payloads                     |
//+------------------------------------------------------------------+
string JsonEscape(const string text)
{
   string result = text;
   result = StringReplace(result, "\\", "\\\\");
   result = StringReplace(result, "\"", "\\\"");
   result = StringReplace(result, "\n", "\\n");
   result = StringReplace(result, "\r", "\\r");
   result = StringReplace(result, "\t", "\\t");
   return result;
}

//+------------------------------------------------------------------+
//| Send message to Telegram via WebRequest                          |
//| NOTE: https://api.telegram.org must be added to the trusted URLs |
//|       list in MT5 (Tools -> Options -> Expert Advisors).         |
//+------------------------------------------------------------------+
bool SendTelegram(const string message)
{
   if(StringLen(TELEGRAM_TOKEN) == 0 || StringLen(TELEGRAM_CHAT_ID) == 0)
      return false;

   string url = "https://api.telegram.org/bot" + TELEGRAM_TOKEN + "/sendMessage";
   string escaped = JsonEscape(message);
   string payload = StringFormat("{\"chat_id\":\"%s\",\"text\":\"%s\",\"parse_mode\":\"HTML\",\"disable_web_page_preview\":true}",
                                 TELEGRAM_CHAT_ID, escaped);
   uchar data[];
   StringToCharArray(payload, data, 0, WHOLE_ARRAY, CP_UTF8);

   uchar result[];
   string headers = "Content-Type: application/json\r\n";
   string response_headers;
   int timeout = 5000;
   int status = WebRequest("POST", url, headers, timeout, data, result, response_headers);
   string response = CharArrayToString(result, 0, -1, CP_UTF8);

   if(status != 200)
   {
      PrintFormat("[Telegram] WebRequest status %d, error %d, response: %s", status, GetLastError(), response);
      return false;
   }

   return true;
}

//+------------------------------------------------------------------+
//| Time helpers (server/GMT basis)                                  |
//+------------------------------------------------------------------+
datetime GetBasisTime()
{
   datetime now = TimeCurrent();
   if(UseGMT)
      return now - (ManualGMTOffsetHours * 3600);
   return now;
}

datetime ToServerTime(const datetime basisTime)
{
   if(UseGMT)
      return basisTime + (ManualGMTOffsetHours * 3600);
   return basisTime;
}

//+------------------------------------------------------------------+
//| Ensure indicator handles are created                             |
//+------------------------------------------------------------------+
bool EnsureIndicators()
{
   if(g_handleEMA == INVALID_HANDLE)
   {
      g_handleEMA = iMA(TradeSymbol, RangeTF, EMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
      if(g_handleEMA == INVALID_HANDLE)
      {
         Print("Failed to create EMA handle");
         return false;
      }
   }

   if(g_handleRSI == INVALID_HANDLE)
   {
      g_handleRSI = iRSI(TradeSymbol, RangeTF, RSIperiod, PRICE_CLOSE);
      if(g_handleRSI == INVALID_HANDLE)
      {
         Print("Failed to create RSI handle");
         return false;
      }
   }

   if(g_handleATR == INVALID_HANDLE)
   {
      g_handleATR = iATR(TradeSymbol, RangeTF, ATRperiod);
      if(g_handleATR == INVALID_HANDLE)
      {
         Print("Failed to create ATR handle");
         return false;
      }
   }

   return true;
}

//+------------------------------------------------------------------+
//| Reset daily state                                                 |
//+------------------------------------------------------------------+
void ResetDailyState(const datetime dayStart)
{
   if(EnableTrading)
   {
      if(g_BuyStopTicket != 0)
      {
         CancelPending(g_BuyStopTicket, "New day reset");
         g_BuyStopTicket = 0;
      }
      if(g_SellStopTicket != 0)
      {
         CancelPending(g_SellStopTicket, "New day reset");
         g_SellStopTicket = 0;
      }
   }

   g_CurrentDayStart  = dayStart;
   g_RangeCalculated  = false;
   g_RangeAnnounced   = false;
   g_TradePlacedToday = false;
   g_SignalSentBuyToday = false;
   g_SignalSentSellToday = false;
   g_PositionActive   = false;
   g_MoveToBE_Done    = false;
   g_LastRiskDistance = 0.0;
   g_LastEntryPrice   = 0.0;
   g_LastStopLoss     = 0.0;
   g_LastSLUpdateTime = 0;

   g_BuyStopTicket    = 0;
   g_SellStopTicket   = 0;
}

//+------------------------------------------------------------------+
//| Calculate Asian session range                                     |
//+------------------------------------------------------------------+
bool CalcAsianRange()
{
   if(g_RangeCalculated)
      return true;

   datetime now = GetBasisTime();
   MqlDateTime tm;
   TimeToStruct(now, tm);
   if(tm.hour < AsianEndHour)
      return false;

   datetime dayStart = now - (tm.hour * 3600 + tm.min * 60 + tm.sec);
   if(dayStart != g_CurrentDayStart)
      ResetDailyState(dayStart);

   datetime rangeStart = dayStart + AsianStartHour * 3600;
   datetime rangeEnd   = dayStart + AsianEndHour * 3600;
   datetime rangeStartServer = ToServerTime(rangeStart);
   datetime rangeEndServer   = ToServerTime(rangeEnd);

   MqlRates rates[];
   int copied = CopyRates(TradeSymbol, RangeTF, rangeStartServer, rangeEndServer, rates);
   if(copied <= 0)
   {
      Print("Failed to copy rates for Asian range");
      return false;
   }

   double high = -DBL_MAX;
   double low  = DBL_MAX;

   for(int i = 0; i < copied; ++i)
   {
      if(rates[i].time >= rangeStartServer && rates[i].time < rangeEndServer)
      {
         high = MathMax(high, rates[i].high);
         low  = MathMin(low,  rates[i].low);
      }
   }

   if(high == -DBL_MAX || low == DBL_MAX)
      return false;

   g_AsianHigh       = high;
   g_AsianLow        = low;
   g_RangeCalculated = true;

   string msg = StringFormat("\xF0\x9F\x9F\xA8 <b>Asian Range</b> %s\nHigh: %.2f  Low: %.2f\nWindow: %02d:00-%02d:59",
                             TradeSymbol, g_AsianHigh, g_AsianLow, AsianStartHour, AsianEndHour - 1);
   if(!g_RangeAnnounced)
   {
      SendTelegram(msg);
      g_RangeAnnounced = true;
   }

   Print(msg);
   return true;
}

//+------------------------------------------------------------------+
//| Retrieve last closed EMA, RSI, ATR values                         |
//+------------------------------------------------------------------+
bool GetIndicatorValues(double &emaValue, double &rsiValue, double &atrValue)
{
   emaValue = 0.0;
   rsiValue = 0.0;
   atrValue = 0.0;

   if(!EnsureIndicators())
      return false;

   double buffer[2];
   if(CopyBuffer(g_handleEMA, 0, 1, 1, buffer) <= 0)
      return false;
   emaValue = buffer[0];

   if(CopyBuffer(g_handleRSI, 0, 1, 1, buffer) <= 0)
      return false;
   rsiValue = buffer[0];

   if(CopyBuffer(g_handleATR, 0, 1, 1, buffer) <= 0)
      return false;
   atrValue = buffer[0];

   return true;
}

//+------------------------------------------------------------------+
//| Calculate trade volume based on risk percentage                   |
//+------------------------------------------------------------------+
double CalcLotsByRisk(const double entry, const double stopLoss, const ENUM_ORDER_TYPE orderType)
{
   double riskInMoney = AccountInfoDouble(ACCOUNT_BALANCE) * (RiskPercent / 100.0);
   double tickValue   = SymbolInfoDouble(TradeSymbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize    = SymbolInfoDouble(TradeSymbol, SYMBOL_TRADE_TICK_SIZE);
   double minLot      = SymbolInfoDouble(TradeSymbol, SYMBOL_VOLUME_MIN);
   double maxLot      = SymbolInfoDouble(TradeSymbol, SYMBOL_VOLUME_MAX);
   double lotStep     = SymbolInfoDouble(TradeSymbol, SYMBOL_VOLUME_STEP);
   int    lotDigits   = (int)SymbolInfoInteger(TradeSymbol, SYMBOL_VOLUME_DIGITS);

   double stopDistance = MathAbs(entry - stopLoss);
   if(stopDistance <= 0.0 || tickValue <= 0.0 || tickSize <= 0.0 || lotStep <= 0.0)
      return 0.0;

   double ticks = stopDistance / tickSize;
   if(ticks <= 0.0)
      return 0.0;

   double lot = riskInMoney / (ticks * tickValue);
   lot = MathMax(minLot, MathMin(maxLot, lot));
   lot = MathFloor(lot / lotStep) * lotStep;
   lot = NormalizeDouble(lot, lotDigits);

   double freeMargin = AccountInfoDouble(ACCOUNT_MARGIN_FREE);
   double margin = 0.0;
   while(lot >= minLot)
   {
      if(!OrderCalcMargin(orderType, TradeSymbol, lot, entry, margin))
      {
         Print("OrderCalcMargin failed for volume check");
         return 0.0;
      }
      if(margin <= freeMargin)
         break;
      lot = NormalizeDouble(lot - lotStep, lotDigits);
   }
   if(lot < minLot)
      return 0.0;
   return lot;
}

//+------------------------------------------------------------------+
//| Check that the spread is acceptable                               |
//+------------------------------------------------------------------+
bool SpreadOK()
{
   double ask = SymbolInfoDouble(TradeSymbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(TradeSymbol, SYMBOL_BID);
   double spreadPoints = (ask - bid) / SymbolInfoDouble(TradeSymbol, SYMBOL_POINT);
   return (spreadPoints <= MaxSpreadPoints);
}

//+------------------------------------------------------------------+
//| Cancel pending order                                              |
//+------------------------------------------------------------------+
void CancelPending(const ulong ticket, const string reason)
{
   if(ticket == 0)
      return;

   if(!EnableTrading)
      return;

   if(!OrderSelect(ticket))
   {
      PrintFormat("Pending order %I64u not found for cancel", ticket);
      return;
   }

   string orderSymbol = OrderGetString(ORDER_SYMBOL);
   long orderMagic = OrderGetInteger(ORDER_MAGIC);
   long orderType = OrderGetInteger(ORDER_TYPE);
   if(orderSymbol != TradeSymbol || orderMagic != MagicNumber)
      return;

   if(orderType != ORDER_TYPE_BUY_STOP && orderType != ORDER_TYPE_SELL_STOP &&
      orderType != ORDER_TYPE_BUY_LIMIT && orderType != ORDER_TYPE_SELL_LIMIT &&
      orderType != ORDER_TYPE_BUY_STOP_LIMIT && orderType != ORDER_TYPE_SELL_STOP_LIMIT)
      return;

   MqlTradeRequest request;
   MqlTradeResult  result;
   ZeroMemory(request);
   ZeroMemory(result);

   request.action   = TRADE_ACTION_REMOVE;
   request.order    = ticket;
   request.symbol   = TradeSymbol;
   request.magic    = MagicNumber;

   if(!OrderSend(request, result))
      PrintFormat("Failed to cancel pending order %I64u. Error %d", ticket, GetLastError());
   else
   {
      string msg = StringFormat("\xF0\x9F\x9B\x91 <b>PENDING CANCELED</b> %s Ticket %I64u (%s)",
                                TradeSymbol, ticket, reason);
      SendTelegram(msg);
   }
}

//+------------------------------------------------------------------+
//| Place pending order                                               |
//+------------------------------------------------------------------+
bool PlacePending(const bool isBuy, const double entry, const double stopLoss, const double takeProfit)
{
   string direction = isBuy ? "BUY STOP" : "SELL STOP";

   if(!EnableTrading)
   {
      if(isBuy && g_SignalSentBuyToday)
         return true;
      if(!isBuy && g_SignalSentSellToday)
         return true;

      string msg = StringFormat("\xF0\x9F\x9F\xA2 <b>SIGNAL</b> %s %s\nEntry %.2f | SL %.2f | TP %.2f\nTrading disabled", TradeSymbol, direction, entry, stopLoss, takeProfit);
      SendTelegram(msg);
      if(isBuy)
         g_SignalSentBuyToday = true;
      else
         g_SignalSentSellToday = true;
      return true;
   }

   if(!SpreadOK())
   {
      Print("Spread too high, aborting pending order placement");
      return false;
   }

   int digits = (int)SymbolInfoInteger(TradeSymbol, SYMBOL_DIGITS);
   double point = SymbolInfoDouble(TradeSymbol, SYMBOL_POINT);
   double ask = SymbolInfoDouble(TradeSymbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(TradeSymbol, SYMBOL_BID);
   int stopsLevel = (int)SymbolInfoInteger(TradeSymbol, SYMBOL_TRADE_STOPS_LEVEL);
   int freezeLevel = (int)SymbolInfoInteger(TradeSymbol, SYMBOL_TRADE_FREEZE_LEVEL);
   int minLevel = MathMax(stopsLevel, freezeLevel);
   double minDistance = minLevel * point;

   double normEntry = NormalizeDouble(entry, digits);
   double normSL = NormalizeDouble(stopLoss, digits);
   double normTP = NormalizeDouble(takeProfit, digits);

   if(isBuy)
   {
      if((normEntry - ask) < minDistance)
      {
         Print("Pending buy stop too close to market or within freeze level");
         return false;
      }
      if((normEntry - normSL) < (stopsLevel * point) || (normTP - normEntry) < (stopsLevel * point))
      {
         Print("SL/TP distances too close to entry for buy stop");
         return false;
      }
   }
   else
   {
      if((bid - normEntry) < minDistance)
      {
         Print("Pending sell stop too close to market or within freeze level");
         return false;
      }
      if((normSL - normEntry) < (stopsLevel * point) || (normEntry - normTP) < (stopsLevel * point))
      {
         Print("SL/TP distances too close to entry for sell stop");
         return false;
      }
   }

   ENUM_ORDER_TYPE pendingType = isBuy ? ORDER_TYPE_BUY_STOP : ORDER_TYPE_SELL_STOP;
   double volume = CalcLotsByRisk(normEntry, normSL, pendingType);
   if(volume <= 0.0)
   {
      Print("Calculated lot size invalid");
      return false;
   }

   MqlTradeRequest request;
   MqlTradeResult  result;
   ZeroMemory(request);
   ZeroMemory(result);

   request.action   = TRADE_ACTION_PENDING;
   request.symbol   = TradeSymbol;
   request.magic    = MagicNumber;
   request.volume   = volume;
   request.price    = normEntry;
   request.sl       = normSL;
   request.tp       = normTP;
   request.deviation= Slippage;
   request.type     = pendingType;
   request.type_filling = ORDER_FILLING_RETURN;

   if(!OrderSend(request, result))
   {
      PrintFormat("OrderSend failed: %d", GetLastError());
      return false;
   }

   if(result.retcode != TRADE_RETCODE_DONE)
   {
      PrintFormat("Pending order rejected. Retcode=%d", result.retcode);
      return false;
   }

   ulong ticket = result.order;
   if(isBuy)
      g_BuyStopTicket = ticket;
   else
      g_SellStopTicket = ticket;

   g_TradePlacedToday = true;

   string msg = StringFormat("\xF0\x9F\xA7\xA2 <b>PENDING SET</b> %s %s @ %.2f\nSL %.2f | TP %.2f | lots %.2f\nTicket %I64u",
                             TradeSymbol, direction, normEntry, normSL, normTP, volume, ticket);
   SendTelegram(msg);
   Print(msg);
   return true;
}

//+------------------------------------------------------------------+
//| Determine if conditions allow placing pending orders              |
//+------------------------------------------------------------------+
void TryPlacePendings()
{
   if(g_TradePlacedToday || !g_RangeCalculated)
      return;

   double emaValue, rsiValue, atrValue;
   if(!GetIndicatorValues(emaValue, rsiValue, atrValue))
      return;

   double point  = SymbolInfoDouble(TradeSymbol, SYMBOL_POINT);
   double buffer = BufferPoints * point;
   double atrSL  = atrValue * SL_ATR_mult;

   double lastClose = 0.0;
   double closeBuffer[1];
   if(CopyClose(TradeSymbol, RangeTF, 1, 1, closeBuffer) > 0)
      lastClose = closeBuffer[0];

   bool emaBull = lastClose > emaValue;
   bool emaBear = lastClose < emaValue;

   bool longOK  = (OnlyOneSideTrend ? emaBull : true) && rsiValue >= RSILongMin && emaBull;
   bool shortOK = (OnlyOneSideTrend ? emaBear : true) && rsiValue <= RSIShortMax && emaBear;

   datetime now = GetBasisTime();
   MqlDateTime tm;
   TimeToStruct(now, tm);
   if(tm.hour < TradeStartHour || tm.hour >= TradeEndHour)
      return;

   if(longOK)
   {
      double entry = g_AsianHigh + buffer;
      double sl    = entry - atrSL;
      double tp    = entry + RR_TP * (entry - sl);
      PlacePending(true, entry, sl, tp);
      if(EnableTrading && g_TradePlacedToday)
         return;
   }

   if(EnableTrading && g_TradePlacedToday)
      return;

   if(shortOK)
   {
      double entry = g_AsianLow - buffer;
      double sl    = entry + atrSL;
      double tp    = entry - RR_TP * (sl - entry);
      PlacePending(false, entry, sl, tp);
   }
}

//+------------------------------------------------------------------+
//| Manage open positions (break-even and trailing)                   |
//+------------------------------------------------------------------+
void ManageOpenPositions()
{
   if(!PositionSelect(TradeSymbol))
      return;

   if((ulong)PositionGetInteger(POSITION_MAGIC) != (ulong)MagicNumber)
      return;

   double volume = PositionGetDouble(POSITION_VOLUME);
   if(volume <= 0.0)
      return;

   g_PositionActive = true;

   double entry      = PositionGetDouble(POSITION_PRICE_OPEN);
   double stopLoss   = PositionGetDouble(POSITION_SL);
   double currentSL  = stopLoss;
   double point      = SymbolInfoDouble(TradeSymbol, SYMBOL_POINT);
   double ask        = SymbolInfoDouble(TradeSymbol, SYMBOL_ASK);
   double bid        = SymbolInfoDouble(TradeSymbol, SYMBOL_BID);
   long   type       = PositionGetInteger(POSITION_TYPE);

   double atrValue;
   double emaDummy, rsiDummy;
   if(!GetIndicatorValues(emaDummy, rsiDummy, atrValue))
      atrValue = 0.0;

   double risk = MathAbs(entry - stopLoss);
   if(risk <= 0.0)
      return;

   if(!g_MoveToBE_Done && MoveToBE_At1R)
   {
      if(type == POSITION_TYPE_BUY)
      {
         if((bid - entry) >= risk)
         {
            currentSL = entry;
            g_MoveToBE_Done = true;
         }
      }
      else if(type == POSITION_TYPE_SELL)
      {
         if((entry - ask) >= risk)
         {
            currentSL = entry;
            g_MoveToBE_Done = true;
         }
      }
   }

   if(g_MoveToBE_Done && TrailAfter1R && atrValue > 0.0)
   {
      double trailDistance = atrValue * Trail_ATR_mult;
      if(type == POSITION_TYPE_BUY)
      {
         double newSL = bid - trailDistance;
         if(newSL > currentSL)
            currentSL = newSL;
      }
      else if(type == POSITION_TYPE_SELL)
      {
         double newSL = ask + trailDistance;
         if(newSL < currentSL)
            currentSL = newSL;
      }
   }

   int digits = (int)SymbolInfoInteger(TradeSymbol, SYMBOL_DIGITS);
   currentSL = NormalizeDouble(currentSL, digits);

   if(MathAbs(currentSL - stopLoss) >= (MinSLUpdatePoints * point) &&
      (TimeCurrent() - g_LastSLUpdateTime) >= MinSLUpdateSeconds)
   {
      MqlTradeRequest request;
      MqlTradeResult  result;
      ZeroMemory(request);
      ZeroMemory(result);

      request.action   = TRADE_ACTION_SLTP;
      request.symbol   = TradeSymbol;
      request.magic    = MagicNumber;
      request.position = PositionGetInteger(POSITION_TICKET);
      request.sl       = currentSL;
      request.tp       = PositionGetDouble(POSITION_TP);

      if(OrderSend(request, result) && result.retcode == TRADE_RETCODE_DONE)
      {
         string msg = StringFormat("\xF0\x9F\x94\xA7 <b>SL UPDATE</b> %s -> %.2f", TradeSymbol, currentSL);
         SendTelegram(msg);
         Print(msg);
         g_LastSLUpdateTime = TimeCurrent();
      }
      else if(result.retcode != TRADE_RETCODE_DONE &&
              result.retcode != TRADE_RETCODE_REQUOTE &&
              result.retcode != TRADE_RETCODE_TRADE_CONTEXT_BUSY)
      {
         PrintFormat("Failed to modify position SL. Retcode=%d", result.retcode);
      }
   }
}

//+------------------------------------------------------------------+
//| Cancel pending orders outside trading window                      |
//+------------------------------------------------------------------+
void CancelExpiredPendings()
{
   if(!EnableTrading)
      return;

   datetime now = GetBasisTime();
   MqlDateTime tm;
   TimeToStruct(now, tm);
   if(tm.hour < TradeEndHour)
      return;

   if(g_BuyStopTicket != 0)
   {
      CancelPending(g_BuyStopTicket, "Window ended");
      g_BuyStopTicket = 0;
   }
   if(g_SellStopTicket != 0)
   {
      CancelPending(g_SellStopTicket, "Window ended");
      g_SellStopTicket = 0;
   }
}

//+------------------------------------------------------------------+
//| OnInit: setup EA                                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   ResetDailyState(0);

   if(StringLen(TradeSymbol) == 0 || !SymbolSelect(TradeSymbol, true))
   {
      Print("TradeSymbol not available or cannot be selected");
      return INIT_FAILED;
   }

   if(!EnsureIndicators())
      return INIT_FAILED;

   string msg = StringFormat("\xF0\x9F\x9A\x80 <b>EA Started</b> %s\nTrading %s", TradeSymbol, EnableTrading ? "ENABLED" : "DISABLED");
   SendTelegram(msg);
   Print(msg);
   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| OnDeinit: send shutdown message                                   |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   if(g_handleEMA != INVALID_HANDLE) IndicatorRelease(g_handleEMA);
   if(g_handleRSI != INVALID_HANDLE) IndicatorRelease(g_handleRSI);
   if(g_handleATR != INVALID_HANDLE) IndicatorRelease(g_handleATR);

   string msg = StringFormat("\xF0\x9F\x9B\x91 <b>EA Stopped</b> %s (reason %d)", TradeSymbol, reason);
   SendTelegram(msg);
   Print(msg);
}

//+------------------------------------------------------------------+
//| OnTick: core logic                                                |
//+------------------------------------------------------------------+
void OnTick()
{
   datetime now = GetBasisTime();
   MqlDateTime tm;
   TimeToStruct(now, tm);
   datetime dayStart = now - (tm.hour * 3600 + tm.min * 60 + tm.sec);

   if(dayStart != g_CurrentDayStart)
      ResetDailyState(dayStart);

   CalcAsianRange();
   TryPlacePendings();
   CancelExpiredPendings();
   ManageOpenPositions();
}

//+------------------------------------------------------------------+
//| Handle trade transactions                                         |
//+------------------------------------------------------------------+
void OnTradeTransaction(const MqlTradeTransaction &trans,
                        const MqlTradeRequest &request,
                        const MqlTradeResult &result)
{
   if(trans.symbol != TradeSymbol)
      return;

   if(trans.type == TRADE_TRANSACTION_DEAL_ADD)
   {
      if(trans.magic != MagicNumber)
         return;

      ulong dealTicket = trans.deal;
      double price     = trans.price;
      double profit    = trans.profit;
      long dealType    = trans.deal_type;

      if(dealType == DEAL_TYPE_BUY || dealType == DEAL_TYPE_SELL)
      {
         g_PositionActive = true;
         g_TradePlacedToday = true;
         g_MoveToBE_Done = false;
         g_LastEntryPrice = price;
         g_LastRiskDistance = 0.0;

         if(PositionSelect(TradeSymbol) && PositionGetInteger(POSITION_MAGIC) == MagicNumber)
         {
            g_LastStopLoss = PositionGetDouble(POSITION_SL);
            g_LastRiskDistance = MathAbs(PositionGetDouble(POSITION_PRICE_OPEN) - g_LastStopLoss);
         }

         string msg = StringFormat("\xE2\x9C\x85 <b>ENTRY</b> %s %s @ %.2f (deal %I64u)",
                                   TradeSymbol,
                                   (dealType == DEAL_TYPE_BUY ? "BUY" : "SELL"),
                                   price, dealTicket);
         SendTelegram(msg);
         Print(msg);

         if(dealType == DEAL_TYPE_BUY && g_SellStopTicket != 0)
         {
            CancelPending(g_SellStopTicket, "Opposite triggered");
            g_SellStopTicket = 0;
         }
         if(dealType == DEAL_TYPE_SELL && g_BuyStopTicket != 0)
         {
            CancelPending(g_BuyStopTicket, "Opposite triggered");
            g_BuyStopTicket = 0;
         }
      }
      else if(dealType == DEAL_TYPE_SL || dealType == DEAL_TYPE_TP || dealType == DEAL_TYPE_CLOSE)
      {
         string label = (dealType == DEAL_TYPE_TP) ? "TP" : (dealType == DEAL_TYPE_SL ? "SL" : "CLOSE");
         string msg = StringFormat("\xF0\x9F\x94\x9A <b>%s</b> %s @ %.2f | P/L %.2f",
                                   label, TradeSymbol, price, profit);
         SendTelegram(msg);
         Print(msg);
         g_PositionActive = false;
         g_MoveToBE_Done = false;
      }
   }
   else if(trans.type == TRADE_TRANSACTION_ORDER_DELETE)
   {
      if(trans.magic != MagicNumber)
         return;

      ulong ticket = trans.order;
      if(ticket == g_BuyStopTicket)
         g_BuyStopTicket = 0;
      if(ticket == g_SellStopTicket)
         g_SellStopTicket = 0;
   }
}
//+------------------------------------------------------------------+
